[project]
name = "pythonadvanced"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexey Tulupov", email = "alexmoscow51@gmail.com" }
]
requires-python = ">=3.15"
dependencies = [
    "click>=8.4.2",
    "email-validator>=2.3.0",
    "flask>=3.1.3",
    "flask-wtf>=1.3.0",
    "platformdirs>=4.11.3",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "ruff>=0.16.3",
    "werkzeug>=3.1.8",
    "wtforms>=3.2.2",
]

[project.scripts]
pythonadvanced = "pythonadvanced:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "ruff>=0.16.3",
]
